DROP TABLE BALANCE CASCADE CONSTRAINTS;

CREATE TABLE BALANCE
(
    ACCOUNTID   VARCHAR2(20)
        CONSTRAINT PK_BALANCE PRIMARY KEY,
    ASSETS      NUMBER NOT NULL,
    LASTUPDATED TIMESTAMP DEFAULT SYSDATE
);

ALTER TABLE BALANCE PARALLEL;
ALTER TABLE BALANCE NOPARALLEL;

INSERT INTO BALANCE (ACCOUNTID, ASSETS, LASTUPDATED)
VALUES ('account', 100000000, SYSDATE);

COMMIT;