		
DROP TABLE BALANCE CASCADE CONSTRAINTS;

CREATE TABLE BALANCE
(
    ACCOUNTID   VARCHAR2(50) NOT NULL,
    ASSET      NUMBER NOT NULL,
    LASTUPDATED TIMESTAMP DEFAULT SYSDATE
);


ALTER TABLE BALANCE PARALLEL;
ALTER TABLE BALANCE NOPARALLEL;

INSERT INTO BALANCE (ACCOUNTID, ASSETS, LASTUPDATED)
VALUES ('account', 100000000, SYSDATE);


INSERT INTO BALANCE
VALUES ('account', 1000000, SYSDATE);



COMMIT;

        
SELECT *
FROM BALANCE
ORDER BY LASTUPDATED DESC;
        
        
INSERT INTO BALANCE VALUES('AACsdasdsdasC', 2345, SYSDATE);        


DESC BALANCE;