DROP TABLE EMP;

CREATE TABLE EMP
(
    EMPID    NUMBER
        CONSTRAINT PK_EMP PRIMARY KEY,
    ADMIN    VARCHAR2(30) NOT NULL,
    PASSWORD VARCHAR2(130) NOT NULL,
    SALT     VARCHAR2(64) NOT NULL
);

DROP SEQUENCE EMPID_SEQ;

CREATE SEQUENCE EMPID_SEQ;

INSERT INTO EMP VALUES (EMPID_SEQ.nextval, 'admin', '+AFeFVlJsbPAvjx2KMooFbs9YXnzKGQK+R5yJ7Ehu67fCbFYizbn7RtWZzGQsrB+c5VXaZyHXowo38lhs7Ht4w==', 'Bs58DfqeMXwc0583cMRw8w==');

COMMIT;