DROP TABLE STOCKORDER;

CREATE TABLE STOCKORDER
(
    ORDERID   NUMBER
        CONSTRAINT PK_ORDER PRIMARY KEY,
    QUANTITY  NUMBER               NOT NULL
        CONSTRAINT CK_ORDER_QUANTITY CHECK (QUANTITY >= 0),
    ORDERDATE DATE DEFAULT SYSDATE NOT NULL,
    STOCKID   NUMBER               NOT NULL,
    EMPID     NUMBER               NOT NULL,
    ACCOUNTID VARCHAR2(20)         NOT NULL
);

ALTER TABLE STOCKORDER
    ADD CONSTRAINT FK_STOCK_ORDER FOREIGN KEY (STOCKID)
        REFERENCES STOCK (STOCKID);

ALTER TABLE STOCKORDER
    ADD CONSTRAINT FK_EMP_ORDER FOREIGN KEY (EMPID)
        REFERENCES EMP (EMPID);

ALTER TABLE STOCKORDER
    ADD CONSTRAINT FK_BALANCE_ORDER FOREIGN KEY (ACCOUNTID)
        REFERENCES BALANCE (ACCOUNTID);

DROP SEQUENCE ORDERID_SEQ;

CREATE SEQUENCE ORDERID_SEQ;
