DROP TABLE PRODUCT_STOCK;

CREATE TABLE PRODUCT_STOCK
(
    PRODUCTID NUMBER,
    STOCKID   NUMBER,
    PRIMARY KEY (PRODUCTID, STOCKID),
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT (PRODUCTID),
    FOREIGN KEY (STOCKID) REFERENCES STOCK (STOCKID)
);
