DROP TABLE PRODUCTIMG;

CREATE TABLE PRODUCTIMG
(
    UUID      VARCHAR2(50)
        CONSTRAINT PK_PRODUCTIMG PRIMARY KEY,
    ABSPATH   VARCHAR2(200) NOT NULL,
    RELPATH   VARCHAR2(200) NOT NULL,
    FILENAME  VARCHAR2(200) NOT NULL,
    PRODUCTID NUMBER        NOT NULL
);

ALTER TABLE PRODUCTIMG
    NOPARALLEL;
ALTER TABLE PRODUCTIMG
    PARALLEL;

ALTER TABLE PRODUCTIMG
    ADD CONSTRAINT FK_PRODUCT_PRODUCTIMG FOREIGN KEY (PRODUCTID)
        REFERENCES PRODUCT (PRODUCTID)
            ON DELETE CASCADE;
