DROP TABLE PRODUCT CASCADE CONSTRAINTS;

CREATE TABLE PRODUCT
(
    PRODUCTID   NUMBER
        CONSTRAINT PK_PRODUCT PRIMARY KEY,
    PRODUCTNAME VARCHAR2(30) NOT NULL,
    CATEGORY    VARCHAR2(30) NOT NULL,
    PRICE       NUMBER           NOT NULL,
    QUANTITY    NUMBER DEFAULT 0 NOT NULL
);

DROP SEQUENCE PRODUCTID_SEQ;

CREATE SEQUENCE PRODUCTID_SEQ;
