DROP TABLE PRODUCT CASCADE CONSTRAINTS;

CREATE TABLE PRODUCT
(
    PRODUCTID   NUMBER
        CONSTRAINT PK_PRODUCT PRIMARY KEY,
    PRODUCTNAME VARCHAR2(30) NOT NULL,
    CATEGORY    VARCHAR2(30) NOT NULL,
    PRICE       NUMBER           NOT NULL
        CONSTRAINT CK_PRODUCT_PRICE CHECK (PRICE >= 0),
    QUANTITY    NUMBER DEFAULT 0 NOT NULL
        CONSTRAINT CK_PRODUCT_QUANTITY CHECK (QUANTITY >= 0)
);

DROP SEQUENCE PRODUCTID_SEQ;

CREATE SEQUENCE PRODUCTID_SEQ;
