DROP TABLE SALE CASCADE CONSTRAINTS;

CREATE TABLE SALE
(
    SALEID   NUMBER
        CONSTRAINT PK_SALE PRIMARY KEY,
    INCOME   NUMBER               NOT NULL,
    SALEDATE DATE DEFAULT SYSDATE NOT NULL,
    MEMBERID NUMBER               NOT NULL
);

ALTER TABLE SALE
    ADD CONSTRAINT FK_MEMBER_SALE FOREIGN KEY (MEMBERID)
        REFERENCES MEMBER (MEMBERID);

DROP SEQUENCE SALEID_SEQ;

CREATE SEQUENCE SALEID_SEQ;
