DROP TABLE STOCK CASCADE CONSTRAINTS;

CREATE TABLE STOCK
(
    STOCKID   NUMBER
        CONSTRAINT PK_STOCK PRIMARY KEY,
    STOCKNAME VARCHAR2(30) NOT NULL,
    PRICE     NUMBER  NOT NULL,
    QUANTITY  NUMBER  NOT NULL,
    STOCKDATE DATE NOT NULL,
    PRODUCTID NUMBER  NOT NULL
);

ALTER TABLE STOCK
    ADD CONSTRAINT FK_PRODUCT_STOCK FOREIGN KEY (PRODUCTID)
        REFERENCES PRODUCT (PRODUCTID);

DROP SEQUENCE STOCKID_SEQ;

CREATE SEQUENCE STOCKID_SEQ;


BEGIN
FOR I IN 1..300
		LOOP
			INSERT INTO STOCK
			VALUES (PCMASTER.STOCKID_SEQ.NEXTVAL, SYSDATE, '신라면', 1000, 100, 1);
END LOOP;
END;

COMMIT;
